global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187','postgres_slave1-exporter:9187','postgres_slave2-exporter:9187' ]
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8080']      