// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/Vasiliy82/otus-hla-homework/backend/internal/domain"
	jwt "github.com/golang-jwt/jwt/v5"

	mock "github.com/stretchr/testify/mock"
)

// SocialNetworkService is an autogenerated mock type for the SocialNetworkService type
type SocialNetworkService struct {
	mock.Mock
}

// AddFriend provides a mock function with given fields: my_id, friend_id
func (_m *SocialNetworkService) AddFriend(my_id domain.UserKey, friend_id domain.UserKey) error {
	ret := _m.Called(my_id, friend_id)

	if len(ret) == 0 {
		panic("no return value specified for AddFriend")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.UserKey, domain.UserKey) error); ok {
		r0 = rf(my_id, friend_id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePost provides a mock function with given fields: userId, message
func (_m *SocialNetworkService) CreatePost(userId domain.UserKey, message domain.PostMessage) (domain.PostKey, error) {
	ret := _m.Called(userId, message)

	if len(ret) == 0 {
		panic("no return value specified for CreatePost")
	}

	var r0 domain.PostKey
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.UserKey, domain.PostMessage) (domain.PostKey, error)); ok {
		return rf(userId, message)
	}
	if rf, ok := ret.Get(0).(func(domain.UserKey, domain.PostMessage) domain.PostKey); ok {
		r0 = rf(userId, message)
	} else {
		r0 = ret.Get(0).(domain.PostKey)
	}

	if rf, ok := ret.Get(1).(func(domain.UserKey, domain.PostMessage) error); ok {
		r1 = rf(userId, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: user
func (_m *SocialNetworkService) CreateUser(user *domain.User) (domain.UserKey, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 domain.UserKey
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.User) (domain.UserKey, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(*domain.User) domain.UserKey); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(domain.UserKey)
	}

	if rf, ok := ret.Get(1).(func(*domain.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePost provides a mock function with given fields: userId, postId
func (_m *SocialNetworkService) DeletePost(userId domain.UserKey, postId domain.PostKey) error {
	ret := _m.Called(userId, postId)

	if len(ret) == 0 {
		panic("no return value specified for DeletePost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.UserKey, domain.PostKey) error); ok {
		r0 = rf(userId, postId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetFeed provides a mock function with given fields: userId
func (_m *SocialNetworkService) GetFeed(userId domain.UserKey) ([]*domain.Post, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetFeed")
	}

	var r0 []*domain.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.UserKey) ([]*domain.Post, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(domain.UserKey) []*domain.Post); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.UserKey) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPost provides a mock function with given fields: userId, postId
func (_m *SocialNetworkService) GetPost(userId domain.UserKey, postId domain.PostKey) (*domain.Post, error) {
	ret := _m.Called(userId, postId)

	if len(ret) == 0 {
		panic("no return value specified for GetPost")
	}

	var r0 *domain.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.UserKey, domain.PostKey) (*domain.Post, error)); ok {
		return rf(userId, postId)
	}
	if rf, ok := ret.Get(0).(func(domain.UserKey, domain.PostKey) *domain.Post); ok {
		r0 = rf(userId, postId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.UserKey, domain.PostKey) error); ok {
		r1 = rf(userId, postId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: id
func (_m *SocialNetworkService) GetUser(id domain.UserKey) (*domain.User, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.UserKey) (*domain.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(domain.UserKey) *domain.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.UserKey) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPosts provides a mock function with given fields: userId, limit, lastPostId
func (_m *SocialNetworkService) ListPosts(userId domain.UserKey, limit int, lastPostId domain.PostKey) ([]*domain.Post, error) {
	ret := _m.Called(userId, limit, lastPostId)

	if len(ret) == 0 {
		panic("no return value specified for ListPosts")
	}

	var r0 []*domain.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.UserKey, int, domain.PostKey) ([]*domain.Post, error)); ok {
		return rf(userId, limit, lastPostId)
	}
	if rf, ok := ret.Get(0).(func(domain.UserKey, int, domain.PostKey) []*domain.Post); ok {
		r0 = rf(userId, limit, lastPostId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.UserKey, int, domain.PostKey) error); ok {
		r1 = rf(userId, limit, lastPostId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: username, password
func (_m *SocialNetworkService) Login(username string, password string) (domain.TokenString, error) {
	ret := _m.Called(username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 domain.TokenString
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (domain.TokenString, error)); ok {
		return rf(username, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) domain.TokenString); ok {
		r0 = rf(username, password)
	} else {
		r0 = ret.Get(0).(domain.TokenString)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: token
func (_m *SocialNetworkService) Logout(token *jwt.Token) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*jwt.Token) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveFriend provides a mock function with given fields: my_id, friend_id
func (_m *SocialNetworkService) RemoveFriend(my_id domain.UserKey, friend_id domain.UserKey) error {
	ret := _m.Called(my_id, friend_id)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFriend")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.UserKey, domain.UserKey) error); ok {
		r0 = rf(my_id, friend_id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Search provides a mock function with given fields: firstName, lastName
func (_m *SocialNetworkService) Search(firstName string, lastName string) ([]*domain.User, error) {
	ret := _m.Called(firstName, lastName)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]*domain.User, error)); ok {
		return rf(firstName, lastName)
	}
	if rf, ok := ret.Get(0).(func(string, string) []*domain.User); ok {
		r0 = rf(firstName, lastName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(firstName, lastName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePost provides a mock function with given fields: userId, postId, newMessage
func (_m *SocialNetworkService) UpdatePost(userId domain.UserKey, postId domain.PostKey, newMessage domain.PostMessage) error {
	ret := _m.Called(userId, postId, newMessage)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.UserKey, domain.PostKey, domain.PostMessage) error); ok {
		r0 = rf(userId, postId, newMessage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSocialNetworkService creates a new instance of SocialNetworkService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSocialNetworkService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SocialNetworkService {
	mock := &SocialNetworkService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
