global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8080']      
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9102']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
